navbar_title = 'Math Club, ISI Kolkata'
footer = "&copy; 2024-2025 by Math Club, ISI Kolkata"
author = "Math Club, ISI Kolkata"
color_scheme = "light"

enable_zooming_js = true
enable_header_anchor = true
enable_toc = true
enable_site_search = true
enable_math = false

# SEO
enable_open_graph = true
enable_twitter_cards = true

# Collapsible Menu
enable_collapsible_toc = true
enable_collapsible_changelogs = false
toc_position = "right"                # "top" | "right"

# Navbar
navbar_show_all_languages = false
navbar_width = "normal"           # "normal" | "wide" | "extra-wide"

[list_layout]
enable_group_by_year = false
enable_show_date = false
enable_pagination = true

# syntax highlight settings
[syntax_highlight]
lib = "prism.js" # "builtin" | "prism.js"

[syntax_highlight.builtin]
enable_code_copy = true

[syntax_highlight.prism]
enable_code_copy = true
enable_line_no = true
